"""remove form_field from action

Revision ID: 398ea160b733
Revises: a56d50e5cbc4
Create Date: 2017-09-18 09:53:31.440366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ea160b733'
down_revision = 'a56d50e5cbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'form_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('form_field', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
