"""made fields non-nullable

Revision ID: 40b27cc01b52
Revises: 398ea160b733
Create Date: 2017-09-18 12:47:32.376967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b27cc01b52'
down_revision = '398ea160b733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actions', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendees', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'consultant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'mdt_vcmg',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('cases', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('meetings', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cases', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cases', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cases', 'mdt_vcmg',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('cases', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cases', 'consultant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendees', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('actions', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('actions', 'assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
