"""Case model proforma fields

Revision ID: 5db7bf372fed
Revises: dab03048a197
Create Date: 2017-09-05 10:08:35.234099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7bf372fed'
down_revision = 'dab03048a197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('clinic_code', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('discussion', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('medical_history', sa.Text(), nullable=False))
    op.add_column('cases', sa.Column('next_opa', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('pre_plan_surgery', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('question', sa.Text(), nullable=False))
    op.add_column('cases', sa.Column('surgery_date', sa.Date(), nullable=True))
    op.drop_column('cases', 'outcome')
    op.create_unique_constraint(None, 'patients', ['hospital_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.add_column('cases', sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cases', 'surgery_date')
    op.drop_column('cases', 'question')
    op.drop_column('cases', 'pre_plan_surgery')
    op.drop_column('cases', 'next_opa')
    op.drop_column('cases', 'medical_history')
    op.drop_column('cases', 'discussion')
    op.drop_column('cases', 'clinic_code')
    # ### end Alembic commands ###
