"""Case planned_surgery field

Revision ID: 7adf12b9ccd2
Revises: 5db7bf372fed
Create Date: 2017-09-05 10:23:56.727239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adf12b9ccd2'
down_revision = '5db7bf372fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pl_surgery', sa.String(length=255), nullable=True))
    op.drop_column('cases', 'pre_plan_surgery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pre_plan_surgery', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cases', 'pl_surgery')
    # ### end Alembic commands ###
