"""Add form_field to action to keep track of changes

Revision ID: b4bb7697ace6
Revises: 8212d18a5848
Create Date: 2017-09-08 10:51:28.497854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bb7697ace6'
down_revision = '8212d18a5848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('form_field', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'form_field')
    # ### end Alembic commands ###
