"""Correct typo in User

Revision ID: f4ae5ac3dde3
Revises: 7adf12b9ccd2
Create Date: 2017-09-05 10:44:16.200969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ae5ac3dde3'
down_revision = '7adf12b9ccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('planned_surgery', sa.String(length=255), nullable=True))
    op.drop_column('cases', 'pl_surgery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pl_surgery', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cases', 'planned_surgery')
    # ### end Alembic commands ###
